### ISSUE TITLE
Feature request: Support for Native Desktop applications

### ISSUE THREAD

**Issue by vpmedia** [GradleFx/GradleFx#141]
Use case scenario:
- application packaged as .EXE
- application uses ANE native extension

Right now only mobile projects are supporting ANEs.

**Comment by mkeller-gms** [comment]
This feature would be awesome as we want to automate building our extendedDesktop (with ANE) as exe-package file. Was there some progress on this topic, is it scheduled, or do you have a sort-of-hack using a recent gradlefx installation?

**Comment by SlevinBE** [comment]
No progress has been made on this topic and currently it isn't scheduled yet. 
If you're looking for a workaround, then the solution proposed in this thread might be helpful: http://support.gradlefx.org/discussions/questions/3577-how-can-i-build-and-create-ane-package-with-gradlefx

**Comment by mkeller-gms** [comment]
Many thanks for your quick response. Correct me, if I'm wrong, your proposed workaround targets "compiling the ane" but I need to "compile an exe including the ane", so "extension" vs "application". So, your workaround is not applicable, at least from my current point of view, please correct me if I'm wrong.

**Comment by SlevinBE** [comment]
I think it does apply to your usecase, since both endpoints (ane extension or exe application) need to be compiled with the ADT compiler, which is being used in the example.
The major difference lies in the arguments which you provide to adt. For an exe application it will be "-target native" instead of "-target ane"

**Comment by mkeller-gms** [comment]
Thanks, seems you have uncovered my unknowingness :), if easily possible, I'm going to share my solution.

**Comment by mzimdars-gms-online-de** [comment]
Hi, just to wrap up this topic, for everybody having the same problem:
I got around this issue without having to build my own packaging command by injecting the needed command line parameters into an 'air' target:

* I misused the TSA configuration to inject the target:
tsa = config.timestampServer+"\" \"-target\" \"native"

* I misused the fileOptions within the air target description to inject the extdir: 
fileOptions = ["-extdir", "libs"]

and - the installer is built :-)

**Comment by vpmedia** [comment]
For anyone who is interested my solution was to shamefully drop using gradlefx and use only gradle + javaexec for packaging:
https://github.com/vpmedia/cryptopp-ane/blob/master/tester/build.gradle (package_exe .. not sure this one is working but you can get the idea)
