### ISSUE TITLE
dependencies on swcAir projects don't link in the corresponding .swc files

### ISSUE THREAD

**Issue by wenslayer** [GradleFx/GradleFx#166]
I first posed this [problem on the support forums](http://support.gradlefx.org/discussions/problems/2212-merged-dependency-doesnt-work-for-swcair), but I believe this is now a bug. The post contains a repro case, and some analysis of where the problem manifests.

The problem seems to be when constructing the project.configuration.files, the type is used as the extension of the library, instead of mapping swcAir -> swc.

I'll see if I can figure out a way to correct this, but I'll file this issue in the mean time in case anybody else has any ideas.

**Comment by SlevinBE** [comment]
fixed by PR #167
