### ISSUE TITLE
Gradle 2.3 causes a deprecation warning

### ISSUE THREAD

**Issue by cshannon** [GradleFx/GradleFx#169]
Line 45 in GradleFxPlugin.groovy adds a build task, however this behavior appears to have been deprecated as of Gradle 2.3 when also using the standard lifecycle plugin and this now causes a warning when building.  The fix appears to be to use the existing build task that already exists instead of trying to create a new one.

**Comment by haysclark** [comment]
This warning?

`Defining custom 'build' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0`

**Comment by chrisweight** [comment]
Yep - that warning!  :)
