### ISSUE TITLE
Packaging tasks do not check if package is already built

### ISSUE THREAD

**Issue by wenslayer** [GradleFx/GradleFx#173]
It appears that the package and packageMobile tasks do not declare their outputs, which means no up-to-date checks are run.

Repro:
* Run package or packageMobile on a project (that obviously provides suitable configuration).
* Confirm package artifact is produced in build directory.
* Re-run same task.

Expected Result:
* Gradle outputs UP-TO-DATE when attempting to perform the packaging task.

Actual Result:
* Gradle rebuilds the package artifact.

**Comment by wenslayer** [comment]
Ouch, this really hurts when using install* and uninstall* tasks, as they will always cause the package to be rebuilt, which can be 10's of minutes in our case. (Just in case you haven't seen this, @SlevinBE)

**Comment by SlevinBE** [comment]
I've seen it, just haven't had the time to fix it ;)

**Comment by wenslayer** [comment]
Can this issue be closed now that #179 has been merged?

**Comment by SlevinBE** [comment]
You're right, it can :)
