### ISSUE TITLE
Compile Flex task is up-to-date after build script changes

### ISSUE THREAD

**Issue by matyasatfp** [GradleFx/GradleFx#182]
Steps to reproduce:
1. compile your app. for example run gradlew installMobile   
2. Make a change to the build script  
3. compile the app again. It will not recompile even though the build script change can lead to a different binary.   

Same thing can happen if you define command line arguments, that change compile flags. for example:

I run `gradlew installMobile -isDebug`

the build script:

```
...
boolean isDebug = hasProperty('isDebug') ? true : false;

additionalCompilerOptions = [
    "-define+=CONFIG::DEBUG,$isDebug"
]
...
```

**Comment by wenslayer** [comment]
By default, the compileFlex task does not declare the properties that affect compilation as inputs to the task (only the contents of the src directory are treated as inputs). While there might be some debate that it should, you can work around it by explicitly declaring it yourself via:
```
compileFlex.inputs.property('additionalCompilerOptions', additionalCompilerOptions)
```

I do this myself for the packageMobile task where I have a command line argument that can affect the airMobile.target property. I use the convention above to ensure that any change to the property causes the task to rerun if it changes.

Kindly give that a try and let us know how it goes.

**Comment by matyasatfp** [comment]
thanks it works!
