### ISSUE TITLE
Determining SDK install location  Ambiguous method overloading for method java.io.File#<init>.

### ISSUE THREAD

**Issue by flashflexpro** [GradleFx/GradleFx#184]
I have JAVA_HOME, GRADLE_HOME, ANDROID_HOME, FLEX_HOME, all set up.

I tried Gradle 2.1/2.4, JDK 1.7/1.8

Please see the stack:

13:19:14.781 [INFO] [gradlefx] Determining SDK install location
13:19:14.818 [ERROR] [org.gradle.BuildExceptionReporter]
13:19:14.833 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
13:19:14.850 [ERROR] [org.gradle.BuildExceptionReporter]
13:19:14.859 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
13:19:14.877 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring project ':flex:swc'.
13:19:14.894 [ERROR] [org.gradle.BuildExceptionReporter] > Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]
13:19:14.927 [ERROR] [org.gradle.BuildExceptionReporter]
13:19:14.945 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
13:19:14.964 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':flex:swc'.
13:19:14.976 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
13:19:14.994 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
13:19:15.003 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
13:19:15.013 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:521)
13:19:15.028 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:82)
13:19:15.040 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:31)
13:19:15.054 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
13:19:15.064 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
13:19:15.086 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
13:19:15.103 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
13:19:15.115 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
13:19:15.129 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
13:19:15.141 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
13:19:15.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
13:19:15.171 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
13:19:15.194 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
13:19:15.205 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
13:19:15.219 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
13:19:15.230 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
13:19:15.241 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
13:19:15.254 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
13:19:15.272 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
13:19:15.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
13:19:15.306 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
13:19:15.320 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
13:19:15.331 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
13:19:15.348 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
13:19:15.358 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
13:19:15.368 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
13:19:15.377 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]
13:19:15.402 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradlefx.configuration.sdk.SdkInstallLocationFactory.createSdkLocation(SdkInstallLocationFactory.groovy:62)
13:19:15.417 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradlefx.configuration.sdk.SdkInstallLocationFactory$createSdkLocation.call(Unknown Source)
13:19:15.426 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradlefx.configuration.sdk.states.AbstractCreateSdkInstallLocationState.process(AbstractCreateSdkInstallLocationState.groovy:50)
13:19:15.434 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradlefx.configuration.sdk.SdkInitState$process.call(Unknown Source)
13:19:15.442 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradlefx.configuration.sdk.SdkInitState$process.call(Unknown Source)
13:19:15.460 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradlefx.configuration.sdk.DefaultSdkInitialisationContext.initSdk(DefaultSdkInitialisationContext.groovy:33)
13:19:15.474 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradlefx.configuration.sdk.SdkInitialisationContext$initSdk.call(Unknown Source)
13:19:15.486 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradlefx.plugins.GradleFxPlugin.initializeSDKs(GradleFxPlugin.groovy:87)
13:19:15.494 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradlefx.plugins.GradleFxPlugin.configure(GradleFxPlugin.groovy:70)
13:19:15.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradlefx.plugins.AbstractGradleFxPlugin$_apply_closure1.doCall(AbstractGradleFxPlugin.groovy:50)
13:19:15.512 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
13:19:15.523 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
13:19:15.532 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
13:19:15.541 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
13:19:15.552 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
13:19:15.560 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
13:19:15.569 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
13:19:15.583 [ERROR] [org.gradle.BuildExceptionReporter]        ... 27 more
13:19:15.592 [ERROR] [org.gradle.BuildExceptionReporter]
13:19:15.605 [LIFECYCLE] [org.gradle.BuildResultLogger]
13:19:15.617 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
13:19:15.629 [LIFECYCLE] [org.gradle.BuildResultLogger]
13:19:15.639 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 14.006 secs

**Comment by SlevinBE** [comment]
The underlying reason is that the flexHome property is null somehow. Now, this is strange since it defaults to the FLEX_HOME environment variable. Are you sure the environment variable is setup correctly and that you're not overriding the flexHome property in any way?

**Comment by flashflexpro** [comment]
My FLEX_HOME is fine, the trick is I did not have %FLEX_HOME%/bin in path, and the error message is too far from that.

Thanks SlevinBE.
