### ISSUE TITLE
error handling for missing FLEX_HOME

### ISSUE THREAD

**Issue by paleozogt** [GradleFx/GradleFx#187]
Right now if a user doesn't have FLEX_HOME setup, the error is extremely obscure:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':swf'.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
  	[class java.lang.String]
  	[class java.net.URI]
```

I have to code up a check for FLEX_HOME myself in my build.gradle in order to give a decent error message.  Can we have gradlefx give a better error message?

**Comment by SlevinBE** [comment]
related to https://github.com/GradleFx/GradleFx/issues/184

**Comment by SlevinBE** [comment]
resolved with commit https://github.com/GradleFx/GradleFx/commit/9974143c3cc0486df8b73769c85c5ac5c4b1d71c

This is now available on the snapshot repository (https://oss.sonatype.org/content/repositories/snapshots) with version 1.2.1-SNAPSHOT.
