### ISSUE TITLE
Cannot auto-install Flex SDK

### ISSUE THREAD

**Issue by shamruk** [GradleFx/GradleFx#192]
```
            > The following error occurred while executing this line:
              /Users/sms/.gradle/gradleFx/sdks/d4261339b0b64544c6ae1bc94ab4ae030a028252/installer.xml:662: The following error occurred while executing this line:
              /Users/sms/.gradle/gradleFx/sdks/d4261339b0b64544c6ae1bc94ab4ae030a028252/installer.xml:873: The following error occurred while executing this line:
              /Users/sms/.gradle/gradleFx/sdks/d4261339b0b64544c6ae1bc94ab4ae030a028252/installer.xml:881: The following error occurred while executing this line:
              /Users/sms/.gradle/gradleFx/sdks/d4261339b0b64544c6ae1bc94ab4ae030a028252/installer.xml:923: Can't get http://sourceforge.net/adobe/flexsdk/code/HEAD/tree/trunk/frameworks/libs/OSMF2_0.swc?format=raw&ts=201507221810 to /Users/sms/.gradle/gradleFx/sdks/d4261339b0b64544c6ae1bc94ab4ae030a028252/frameworks/libs/osmf.swc
```

http://sourceforge.net/adobe/flexsdk/code/HEAD/tree/trunk/frameworks/libs/OSMF2_0.swc?format=raw&ts=201507221810

link returns "503 Service Unavailable"
Is there a way to set custom link instead?

**Comment by shamruk** [comment]
due to their twitter https://twitter.com/sfnet_ops they will fix the problem soon, but sourcefodge had always been a buggy service

**Comment by SlevinBE** [comment]
There is no way to set a custom link. Installation of the SDK is one thing were GradleFx tries to do as little custom actions as possible, to avoid incompatibilities in the future. Therefore it will probably stay this way.
Let's hope adobe switches to another (more reliable) repository soon.
