### ISSUE TITLE
Cannot auto-install Flex SDK with version 1.3.0

### ISSUE THREAD

**Issue by shamruk** [GradleFx/GradleFx#193]
For some reason I'm getting "The Flex/AIR home location isn't specified" on one computer. I get it even on sample auto-install project after changing gradlefx version to 1.3.0 (btw 1.2.0 works right fine). The strange thing it works on different mac.

**Comment by SlevinBE** [comment]
This is probably related to https://github.com/GradleFx/GradleFx/commit/9974143c3cc0486df8b73769c85c5ac5c4b1d71c
I'll see if I can get a fix in tonight

**Comment by shamruk** [comment]
Looking forward, thanks!

**Comment by SlevinBE** [comment]
fixed with https://github.com/GradleFx/GradleFx/commit/8d2be63d5bdc79871f90fbfc6649ff6ccf5558c1
available now on our snapshot repo as version 1.3.1-SNAPSHOT.
I'll be making this a release asap given the criticality of this bug.

**Comment by shamruk** [comment]
Best support ever! I will check it first thing tomorrow

**Comment by SlevinBE** [comment]
How did it go?

**Comment by shamruk** [comment]
works great, thanks
