### ISSUE TITLE
ADT: Support -connect flag

### ISSUE THREAD

**Issue by wenslayer** [GradleFx/GradleFx#199]
Similar to #197, support the `-connect` flag (with accompanying value). This is needed for debugging packages.

**Comment by wenslayer** [comment]
Reference:
* [Adobe AIR - iOS packages](http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac35eb7b4e12cddc5fbbb-8000.html)

**Comment by SlevinBE** [comment]
solved by PR #201
