### ISSUE TITLE
uninstallMobile fails when no app is installed on the device, and compileFlex + packageMobile are UP-TO-DATE

### ISSUE THREAD

**Issue by psmtec-dklein** [GradleFx/GradleFx#205]
hi, just trying out gradle+gradlefx for the first time today, and i run into a problem with installMobile.

c:\xxx> gradlew installMobile
:aaa:copyresources
:aaa:compileFlex
:aaa:packageMobile
:aaa:uninstallMobile
[ant:java] Java Result: 14
:aaa:installMobile
BUILD SUCCESSFUL

then manually delete the app from the device, and run the build again

c:\xxx> gradlew installMobile
:aaa:copyresources
:aaa:compileFlex UP-TO-DATE
:aaa:packageMobile UP-TO-DATE
:aaa:uninstallMobile
[ant:java] Java Result: 14
Failed to find package xxx.yyy.zzz
:aaa:uninstallMobile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':aaa:uninstallMobile'.
> java.lang.Exception: uninstall app to target device failed: Failed to find package xxx.yyy.zzz

BUILD FAILED

So, is there any way to skip the failed uninstallMobile in this case as well?

(Doing a :aaa:clean and a rebuild is a workaround for now, but pretty inconvenient and time consuming)

---

Gradle 2.3
Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274
Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Windows 7 6.1 amd64
and GradleFx version 1.3.1

**Comment by matyasf** [comment]
I have encountered the same issue, will submit a PR later today

**Comment by matyasf** [comment]
https://github.com/GradleFx/GradleFx/pull/207 should fix it

**Comment by psmtec-dklein** [comment]
Sweet, it does install the app now. (It says failed after installation b/c i guess uninstall failed, but thats just a minor issue for me)

**Comment by SlevinBE** [comment]
merged PR #207
