### ISSUE TITLE
Cannot apply plugins that extend 'java' and 'gradlefx' at the same time

### ISSUE THREAD

**Issue by edeesis** [GradleFx/GradleFx#208]
Right now we have a subproject that contains all of our flex ui, and other projects that do other things.

The final output of the flex ui subproject should be a .war file that contains all the assets, .swf files, etc.

Since the war plugin extends java, and since gradlefx and java have a conflict on the 'test' task, you get the error message:

'Failed to apply plugin [id 'gradlefx']
'Cannot add task 'test' as a task with that name already exists.'

This happens no matter the order. If you do

apply plugin 'gradlefx'
apply plugin 'war'

The message changes to 

'Failed to apply plugin [id 'org.gradle.api.plugins.JavaPlugin']

**Comment by wenslayer** [comment]
Similar to how GradleFx had to rename `publish` to `publishFx`, it looks like we'll need to do the same for `test` (to `testFx`). There may be other tasks that conflict with other plugins as well.

**Comment by edeesis** [comment]
At least, you'd probably have to do clean, the java plugin defines that as well. I'm sure if test was changed to testFx, gradle would complain about that next.

**Comment by paleozogt** [comment]
+1 I have a fairly polyglot project that uses flex, js, and java

**Comment by paleozogt** [comment]
can we get @edeesis's pull-request merged?
