### ISSUE TITLE
flexHome property is null when using File-based dependency for SDK Auto-Install

### ISSUE THREAD

**Issue by edeesis** [GradleFx/GradleFx#212]
In order to make things more universal across multiple dev and build machines, my project is using File-based dependency declaration for the flex SDK.

However, when trying to access the flexHome variable to be used for additionalCompilerOptions, flexHome is null.

I have tried both 'flexHome' and 'project.flexHome', neither seem to be working.

**Comment by edeesis** [comment]
After a little more investigation, from what I can tell, the property gets set late in the configuration phase.

When I do println in the execution phase in a later task, flexHome is set, however, when I use flexHome as a variable in the additionalCompilerOptions, it sets the value as null, even if the variable is set later.

**Comment by SlevinBE** [comment]
This is because of the Gradle lifecycle. To make sure the flexHome variable is available you need to use an afterEvaluate block:

    afterEvaluate {
        additionalCompilerOptions = [
            //use flexHome here
        ]
    }

**Comment by edeesis** [comment]
Yup, that's exactly what I ended up doing. I guess it makes sense and really isn't a bug persay, but maybe it's something that could be called out in the docs?

**Comment by johnmj** [comment]
I had the same issue - println flexHome works perfectly. But when I try to use ${flexHome} in the dependencies section it returns "null" . I had to set the FLEX_HOME in the shell and then the ${flexHome} worked fine.
