### ISSUE TITLE
SDK autoinstall breaks when using AIR with Flex 4.6

### ISSUE THREAD

**Issue by jlopez** [GradleFx/GradleFx#217]
When declaring the following flex sdk dependency:

    // artifactPattern 'http://download.macromedia.com/pub/flex/sdk/[module]_[revision].[ext]'
    flexSDK group: 'org.apache', name: 'flex_sdk', version: '4.6', ext: 'zip'

the SDK autoinstall feature will fail to overlay the AIR SDK on top of the extracted Flex SDK.

This is because the Air Sdk installer looks for `lib/adt.jar`, which happens to be present in this particular Flex SDK.

**Comment by SlevinBE** [comment]
PR has been merged.

**Comment by SlevinBE** [comment]
Little bit after the fact, but I noticed that Flex 4.6 does come bundled with the AIR SDK (see https://helpx.adobe.com/flash-builder/release-note/flex-4-6-sdk-release.html). So in fact the lib/adt.jar is a valid file to detect the AIR SDK.

However, I do like your approach with the sentry files, as it allows one to overlay this specific Flex SDK with another AIR SDK (even while this is discouraged by Adobe). It also has a certain kind of clearness to it. So I will keep this, but with a fallback to the old approach in case the user specifies the Flex/AIR sdk manually with the 'flexhome' property.

**Comment by SlevinBE** [comment]
Fallback mechanism: https://github.com/GradleFx/GradleFx/commit/683d7aaa66585a87e6cbaadd556685274118aab9

**Comment by jlopez** [comment]
Interesting about 4.6. It must be a really old version of air that is bundled, since the way I noticed that the Air SDK wasn't being downloaded was because the resulting SDK failed to compile my Air project (missing things like Event.SUSPEND which were added back in 3.3)

Thanks for the merge.

**Comment by SlevinBE** [comment]
Probably because Flex 4.6 is also quite old by now, it's still from the Adobe days. Now that Flex is under the Apache flag I think it reached 4.14 already.
