### ISSUE TITLE
Unable to build the example projects using the latest GradleFX1.3.3

### ISSUE THREAD

**Issue by heitara** [GradleFx/GradleFx#229]
Hello, 
I'm facing the following problem:

* Where:
Build file '.../GradleFx-Examples/multiproject-all-conventions/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'multiproject-all-conventions'.
> the number of constructors during runtime and compile time for org.gradlefx.configuration.Configurations do not match. Expected -1 but got 1

_I've added the source code of the latest release(1.3.3) to the buildSrc/build/src._
This is the build.gradle file:

    buildscript {
	repositories {
		mavenLocal()
		mavenCentral()
	}
	dependencies {
		classpath group: 'commons-io', name: 'commons-io', version: '2.5'
		classpath group: 'org.gradlefx', name: 'gradlefx', version: '1.3.3'

	}
}
    
    subprojects {

	apply plugin: 'gradlefx'

	//default configuration 
	
}

    task wrapper(type: Wrapper) {
    group = 'Buildmaster'
    description = 'Generates gradlew and gradlew.bat bootstrap scripts'
    gradleVersion = '2.1'
    // place jar file and properties into a subdirectory to avoid root dir clutter
    jarFile = 'buildSrc/wrapper/gradle.jar'
}

**Comment by SlevinBE** [comment]
I think it gives you this error because you use a non-supported configuration type for your dependencies, namely 'classpath'. You can find the supported configuration types here: http://doc.gradlefx.org/en/latest/dependency_management.html

**Comment by heitara** [comment]
Nope, the class path is there to reference the missing dependency. If you remove it then gradle complains that commons-io.jar is missing. So, it's not that.

This level in the gradle file is to be able to build/compile gradlefx code.

**Comment by SlevinBE** [comment]
oh indeed, you're right, it's located in the buildscript{} section.

**Comment by SlevinBE** [comment]
Are you running it with the gradle wrapper (gradlew compile) or your local gradle installation (gradle compile)?

**Comment by heitara** [comment]
I'm running it using my installation of gradle. Simply,
Executing 'gradle' in the terminal. I'm using Mac OS if that helps and gradle 2+

**Comment by heitara** [comment]
Do you think that you could update the example projects, which are supposed to be using gradlefx? They are not working.

**Comment by SlevinBE** [comment]
Yesterday I updated all example project to GradleFx 1.3.3, which now all successfully compile on my machine (Windows since I don't have a Mac atm, but in theory shouldn't matter for the issue you get).

Also tried out Gradle 2.0 and 2.13, because sometimes their core api changes, which GradleFx uses. But that also went fine. So right now I'm trying to reproduce the issue.

**Comment by heitara** [comment]
I'll check it and get back to you

**Comment by heitara** [comment]
Here is what ```gradle -v``` prints:
picked up _JAVA_OPTIONS: -Xmx512m

------------------------------------------------------------
Gradle 1.8
------------------------------------------------------------

Build time:   2013-09-24 07:32:33 UTC
Build number: none
Revision:     7970ec3503b4f5767ee1c1c69f8b4186c4763e3d

Groovy:       1.8.6
Ant:          Apache Ant(TM) version 1.9.2 compiled on July 8 2013
Ivy:          2.2.0
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.11.4 x86_64

Then I've updated my default gradle installation to much recent version:

------------------------------------------------------------
Gradle 2.9
------------------------------------------------------------

Build time:   2015-11-17 07:02:17 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.11.4 x86_64

Now I'm able to compile the examples. I guess that the default version which was used to run the gradleFx scripts was 1.8 and this was causing the problems from above. Thanks for you help, now everything is working as expected.

**Comment by SlevinBE** [comment]
small tip: try using the Gradle wrapper when it's included in a Gradle project, then you can be certain the correct version of Gradle will be used for the project. You can use the gradle wrapper by calling "gradlew" instead of "gradle" in the project directory. :-)
