### ISSUE TITLE
Gradle 3.0 - Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.

### ISSUE THREAD

**Issue by tepsl** [GradleFx/GradleFx#235]
It seems GradleFx plugin is incompatible with Gradle 3.0.
The error message is:

> Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.

I think this error message is related to below description at Gradle 3.0 Release note (Changes to previously deprecated APIs);

> Declaring custom check, clean, build or assemble tasks is not allowed anymore when using the lifecycle plugin.

[https://docs.gradle.org/3.0/release-notes](url)

**Comment by mrgmatthews** [comment]
Can a patch of this fix be released?

**Comment by SlevinBE** [comment]
I was reviewing and validating #236 yesterday, but didn't merge it yet (because of some other issue, not related to the PR). I'll release a new version of GradleFx once #236 is merged.

**Comment by rferrerasm** [comment]
Any news on this? Thanks.

**Comment by SlevinBE** [comment]
I've just released GradleFx 1.4.0 which includes this fix. Sorry for the delay, last few months have been very busy.

**Comment by rferrerasm** [comment]
Thank you.

**Comment by flashflexpro** [comment]
Thank you very much!
