### ISSUE TITLE
Is it possible to auto-install with beta channel AIR SDK?

### ISSUE THREAD

**Issue by shamruk** [GradleFx/GradleFx#239]
I need to switch to Adobe AIR 24 beta. How can I configure auto-install this SDK?

**Comment by SlevinBE** [comment]
First of all, sorry for the late response. 
You can use a url-based dependency to this sdk. I think something like this should work:

```
repositories {
        ivy {
                name 'Adobe Air SDK'
                artifactPattern 'https://fpdownload.macromedia.com/pub/labs/flashruntimes/air/[module].[ext]'
        }
}
```
```
dependencies {
        airSDK  group: 'com.adobe', name: 'AIRSDK_Compiler', version: '3.4', ext: 'zip'
    }
```

**Comment by shamruk** [comment]
AIR 24 is out, but looks like has ".dmg" extension (for mac) now
http://download.macromedia.com/air/mac/download/24.0/AdobeAIRSDK.dmg
Gives me 
`Unsupported sdk packaging type. Supported formats are zip, tar.gz and tbz2`

**Comment by SlevinBE** [comment]
argh, dmg extractions isn't an easy one to add :(
Currently the easiest alternative will be to repackage the dmg yourself to a tar.gz, and host it somewhere. However, not sure how long this will last, given the reason of this change on Adobe's part described in this Flex JIRA issue: https://issues.apache.org/jira/browse/FLEX-35166

**Comment by SlevinBE** [comment]
Closing this one, since there's another ticket tackling the AIR 24 issue. #241
