### ISSUE TITLE
Target = 'bundle' signed application with captive runtime

### ISSUE THREAD

**Issue by railnation** [GradleFx/GradleFx#243]
Hi,

I like to ask if it is possible to package and sign an application with the targe='bundle' which generates a desktop exe.

If I try I receive the following error :

[org.gradle.api.internal.project.ant.AntLoggingAdapter] Setting project property: adtError -> Signing options required to package from descriptor and fileset

Thanks

**Comment by railnation** [comment]
`C:\perforce\csobolewski_europe_next_version\07_sdk\air_24_0_0_180\bin\adt.bat
    -package
    -storetype
    pkcs12
    -keystore
    *.p12
    -storepass
    **
    -target
    bundle *.exe application_steam.xml
    -extdir C:\ane
    -extdir C:\android
    -C Railnation.swf`

this command line works, it is generated by our Development IDE.

`'adt.jar'
'-package'
'-target'
'bundle'
'-storetype'
'pkcs12'
'-keystore'
'*.p12'
'-storepass'
'**'
'*.exe'
'application_steam.xml'
'-C'
'Railnation.swf'`

this one is generated by gradle fx and fails

**Comment by SlevinBE** [comment]
I see that you are abusing the airMobile options to specify the 'target' property, while also using the packageMobile target to actually package a desktop app. This is causing some issues :)

GradleFx currently doesn't support a custom 'target' property when using the standard 'package' task with an 'air' project type. So it can only output a .air package, which can then be installed on a desktop pc.

'mobile' project types do allow to specify a custom 'target' (with the airMobile.target option), but their packaging process is tailored to mobile packaging types.

The adt packaging tool (provided with the SDK and which is used by GradleFx) expects its options in a certain sequence, which differs between packaging targets. 
For mobile packaging targets, the 'target' option has to come first, with the signing options coming right after it.
However, for 'bundle' targets the signing options have to come first, then the target option, and then optionally a second set of signing options. (see http://help.adobe.com/en_US/air/build/WSfffb011ac560372f709e16db131e43659b9-8000.html#WSfffb011ac560372f-63d4a6d6131f383b813-8000). This is the reason why you are seeing this error.

So using the standard GradleFx options/tasks for packaging the application don't seem like a solution for you. Your best bet is to create a custom Gradle task which calls the adt.jar itself with all the right options, which is run after GradleFx has finished compilation of your project.

**Comment by railnation** [comment]
Okay thank you for your reply!
