### ISSUE TITLE
build leads to "UP-TO-DATE" for cleaned projects

### ISSUE THREAD

**Issue by shamruk** [GradleFx/GradleFx#257]
I'am using 1.5.1-SNAPSHOT (it can make new air SDKs on mac).
After making some changes "gradle build" ran in seconds with "UP-TO-DATE" status.
Used "gradle clean" - same result.
Removed all target folders - same result: ran in seconds and no swf (because i've deleted the old one).
Rolled back to 1.3.0 gradlefx version and it worked great.

**Comment by shamruk** [comment]
Found the problem, all works find using compile task
Looks like i'm using different commands in different brunches:
compile, build, buildFx and compileFlex.
Witch of them is the most correct way to make swf files?

**Comment by SlevinBE** [comment]
both compileFlex and buildFx should work to create a swf, as that is how they're named in GradleFx. BuildFx is basically a task which combines compileFlex and testFx.

**Comment by shamruk** [comment]
thanks
