### ISSUE TITLE
gradlefx 0.6.4 and gradle 1.5 rc3 - conflict with maven-publish plugin

### ISSUE THREAD

**Issue by patrickw-nf** [GradleFx/GradleFx#91]
I tested this issue by running:

gradle tasks --info

When maven-publish is applied before gradlefx I get this error:

Cannot add task ':publish' as a task with that name already exists.

When maven-publish is applied after gradlefx I get this error:

The 'type' property hasn't been specified! This property is required. Possible values are: [swf, swc, air, mobile]

**Comment by paleozogt** [comment]
+1 We can't publish artifacts from gradlefx

**Comment by SlevinBE** [comment]
fixed: GradleFx's publish task has been renamed to publishFx
